from datetime import datetime

def generate_report(filename, extracted_text, analysis_result):

    report = f"""
DIGITAL FORENSIC ANALYSIS REPORT
---------------------------------

File Name: {filename}
Analysis Date: {datetime.now()}

---------------------------------
EXTRACTED DATA
---------------------------------

{extracted_text}

---------------------------------
AI ANALYSIS RESULT
---------------------------------

{analysis_result}

---------------------------------
Conclusion:
This report was automatically generated by the
Automated Digital Forensics Reporter system.
"""

    return report